CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/rest_exchange.py
resolves https://github.com/Drakkar-Software/OctoBot-Trading/issues/20
=> [CCXT] fixed 'find_market' removed method

octobot_trading/exchanges/exchange_manager.pxd, octobot_trading/exchanges/exchange_manager.py
=> [Syntax] Fix exchange manager

octobot_trading/exchanges/exchange_manager.pxd, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/exchanges.pxd, octobot_trading/exchanges/exchanges.py, tests/exchanges/test_exchange_factory.py, tests/exchanges/test_exchanges.py
Related to https://github.com/Drakkar-Software/OctoBot/pull/1009#discussion_r362193484
requires #27
=> [Proposal] Add exchange ID 

octobot_trading/channels/balance.py, octobot_trading/channels/exchange_channel.py, octobot_trading/channels/kline.py, octobot_trading/channels/ohlcv.py, octobot_trading/channels/order_book.py, octobot_trading/channels/orders.py, octobot_trading/channels/positions.py, octobot_trading/channels/price.py, octobot_trading/channels/recent_trade.py, octobot_trading/channels/ticker.py, octobot_trading/channels/trades.py, octobot_trading/cli/cli_tools.py, octobot_trading/exchanges/data/exchange_config_data.py, octobot_trading/exchanges/exchanges.pxd, octobot_trading/exchanges/exchanges.py, octobot_trading/producers/abstract_mode_producer.py, octobot_trading/producers/balance_updater.py, octobot_trading/producers/prices_updater.py, octobot_trading/producers/simulator/orders_updater_simulator.py, tests/exchanges/test_exchanges.py
Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/60
=> [ExchangeChannel] Add exchange id in channel notifications

CHANGELOG.md, README.md, octobot_trading/__init__.py
- Exchange ID in ExchangeChannels notifications
=> [Version] v1.4.13

octobot_trading/exchanges/data/exchange_config_data.pxd, octobot_trading/exchanges/data/exchange_config_data.py, octobot_trading/exchanges/exchanges.pxd, octobot_trading/exchanges/exchanges.py, tests/exchanges/data/test_exchange_config_data.py
Requires #54
Related to https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/13
=> [ExchangeConfig] Add cryptocurrencies attribute 

octobot_trading/producers/abstract_mode_producer.py
Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/19
=> [Matrix] migrate callback

octobot_trading/producers/abstract_mode_producer.py
Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/18
=> [Evaluator] Add matrix_id

octobot_trading/api/exchange.py, octobot_trading/api/orders.py, octobot_trading/channels/exchange_channel.pxd, octobot_trading/channels/exchange_channel.py, octobot_trading/cli/cli_tools.py, octobot_trading/data/portfolio_profitability.py, octobot_trading/exchanges/data/exchange_personal_data.py, octobot_trading/exchanges/exchange_factory.py, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/exchange_simulator.py, octobot_trading/exchanges/exchanges.py, octobot_trading/exchanges/websockets/octobot_websocket.py, octobot_trading/producers/abstract_mode_producer.py, octobot_trading/producers/balance_updater.py, octobot_trading/producers/prices_updater.py, octobot_trading/producers/simulator/orders_updater_simulator.py, tests/exchanges/test_exchange_factory.py
requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/25 to be approved
=> [ExchangeChannel] Migrate form exchange name to exchange id

CHANGELOG.md, README.md, octobot_trading/__init__.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/76
=> [Version] v1.4.16 

octobot_trading/api/exchange.py, octobot_trading/api/portfolio.py, octobot_trading/exchanges/exchange_manager.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/87
=> Update APIs for backtesting

octobot_trading/api/modes.py, octobot_trading/channels/mode.pxd, octobot_trading/channels/mode.py, octobot_trading/consumers/abstract_mode_consumer.pxd, octobot_trading/consumers/abstract_mode_consumer.py, octobot_trading/exchanges/exchange_builder.py, octobot_trading/modes/abstract_trading_mode.pxd, octobot_trading/modes/abstract_trading_mode.py, octobot_trading/producers/abstract_mode_producer.pxd, octobot_trading/producers/abstract_mode_producer.py
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/72
=> [AbstractMode] Manage symbol and time frame non-wildcard  

octobot_trading/data/order.pxd, octobot_trading/data/order.py, octobot_trading/exchanges/abstract_exchange.pxd, octobot_trading/exchanges/abstract_exchange.py, octobot_trading/exchanges/exchange_simulator.pxd, octobot_trading/exchanges/exchange_simulator.py, octobot_trading/orders/types/buy_limit_order.py, octobot_trading/orders/types/buy_market_order.py, octobot_trading/orders/types/sell_limit_order.py, octobot_trading/orders/types/sell_market_order.py, octobot_trading/orders/types/stop_loss_limit_order.py, octobot_trading/orders/types/stop_loss_order.py, octobot_trading/orders/types/trailing_stop_order.py, octobot_trading/producers/simulator/orders_updater_simulator.py, octobot_trading/producers/simulator/recent_trade_updater_simulator.py, octobot_trading/producers/simulator/ticker_updater_simulator.py
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/15
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/17
=> [Backtesting] update orders management and price channel

octobot_trading/exchanges/data/exchange_config_data.py, octobot_trading/exchanges/exchange_manager.pxd, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/exchange_simulator.pxd, octobot_trading/exchanges/exchange_simulator.py, octobot_trading/producers/simulator/__init__.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/87
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/20
=> [Backtesting] Run backtesting on required timeframes only 

octobot_trading/api/exchange.py, octobot_trading/api/profitability.py, octobot_trading/channels/exchange_channel.py, octobot_trading/consumers/abstract_mode_consumer.py, octobot_trading/data/portfolio_profitability.pxd, octobot_trading/data/portfolio_profitability.py, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/exchange_simulator.py, octobot_trading/producers/abstract_mode_producer.pxd, octobot_trading/producers/abstract_mode_producer.py, octobot_trading/producers/balance_updater.pxd, octobot_trading/producers/balance_updater.py, octobot_trading/producers/simulator/__init__.py, octobot_trading/producers/simulator/kline_updater_simulator.py, octobot_trading/producers/simulator/ohlcv_updater_simulator.py, octobot_trading/producers/simulator/order_book_updater_simulator.py, octobot_trading/producers/simulator/price_updater_simulator.py, octobot_trading/producers/simulator/recent_trade_updater_simulator.py, octobot_trading/producers/simulator/simulator_updater_utils.py, octobot_trading/producers/simulator/ticker_updater_simulator.py, octobot_trading/producers/ticker_updater.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/89
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/19
requires https://github.com/Drakkar-Software/OctoBot-Channels/pull/20
=> [Backtesting] Independant backtesting update

octobot_trading/api/symbol_data.py, octobot_trading/api/trades.py, octobot_trading/cli/cli_tools.py, octobot_trading/data/trade.py, octobot_trading/data_manager/prices_manager.py, octobot_trading/exchanges/data/exchange_symbols_data.pxd, octobot_trading/exchanges/data/exchange_symbols_data.py, octobot_trading/traders/trader.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/90
=> Update api 

octobot_trading/api/modes.py, octobot_trading/exchanges/exchange_builder.py, octobot_trading/exchanges/exchange_manager.pxd, octobot_trading/exchanges/exchange_manager.py, octobot_trading/modes/abstract_trading_mode.pxd, octobot_trading/modes/abstract_trading_mode.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/93
=> Add trading modes into exchange manager

requirements.txt
https://travis-ci.org/Drakkar-Software/OctoBot-Trading/jobs/651393514#L2168
=> [Requirement] Fix idna version for requests 

requirements.txt
Depends on https://github.com/Drakkar-Software/OctoBot-Websockets/pull/20
=> [Requirements] Update

octobot_trading/producers/kline_updater.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/19
=> improve kline error management 

octobot_trading/channels/balance.py, octobot_trading/channels/kline.py, octobot_trading/channels/ohlcv.py, octobot_trading/channels/order_book.py, octobot_trading/channels/orders.py, octobot_trading/channels/positions.py, octobot_trading/channels/price.py, octobot_trading/channels/recent_trade.py, octobot_trading/channels/ticker.py, octobot_trading/channels/trades.py, octobot_trading/data/portfolio_profitability.py, octobot_trading/data_manager/portfolio_manager.py, octobot_trading/exchanges/data/exchange_config_data.py, octobot_trading/exchanges/data/exchange_personal_data.py, octobot_trading/exchanges/websockets/abstract_websocket.py, octobot_trading/exchanges/websockets/octobot_websocket.py, octobot_trading/producers/abstract_mode_producer.py, octobot_trading/producers/balance_updater.py, octobot_trading/producers/ohlcv_updater.py, octobot_trading/producers/order_book_updater.py, octobot_trading/producers/positions_updater.py, octobot_trading/producers/prices_updater.py, octobot_trading/producers/recent_trade_updater.py, octobot_trading/producers/simulator/ohlcv_updater_simulator.py, octobot_trading/producers/simulator/orders_updater_simulator.py, octobot_trading/producers/ticker_updater.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/19
=> update exception logger 

octobot_trading/channels/positions.py, octobot_trading/data/position.pxd, octobot_trading/data/position.py, octobot_trading/data_manager/positions_manager.py, octobot_trading/enums.py, octobot_trading/exchanges/data/exchange_personal_data.py, octobot_trading/producers/positions_updater.py
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/126
=> [Positions] Improve position management 

requirements.txt
Add bybit support : https://github.com/ccxt/ccxt/issues/5070
=> [Requirement] Update ccxt requirement 

octobot_trading/enums.py, octobot_trading/exchanges/margin/margin_exchange.py
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/129
=> Add margin type support

CHANGELOG.md, README.md, octobot_trading/__init__.py
- [Channels] 
- Book Ticker
- Mini Ticker
- Liquidations
- [Websocket] keep alive
=> [Version] v1.4.22

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/api/modes.py, octobot_trading/channels/__init__.py, octobot_trading/exchanges/exchange_manager.py, requirements.txt
=> Fix imports

CHANGELOG.md, README.md, octobot_trading/__init__.py
=> [Version] v1.4.24

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/consumers/abstract_mode_consumer.pxd, octobot_trading/consumers/abstract_mode_consumer.py, octobot_trading/data_manager/candles_manager.pxd, octobot_trading/data_manager/candles_manager.py
- CandleManager cython headers
- AbstractModeConsumer cython headers
=> Fix cython headers 

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/channels/exchange_channel.pxd, octobot_trading/channels/exchange_channel.py, octobot_trading/channels/kline.pxd, octobot_trading/channels/kline.py, octobot_trading/channels/ohlcv.pxd, octobot_trading/channels/ohlcv.py, octobot_trading/exchanges/exchange_manager.py, requirements.txt
- [Channel] time frame filter
- symbols_by_crypto_currencies instead of currencies in exchanges
=> [Version] v1.4.27 

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/channels/mode.pxd, octobot_trading/channels/mode.py, octobot_trading/producers/abstract_mode_producer.py, requirements.txt
- [ModeChannel] data param to consumers callback
- [ModeChannel] consumer filtering by state
- [AbstractModeProducer] Matrix channel subscription
=> [Version] v1.5.1 

.gitignore, CHANGELOG.md, README.md, dev_requirements.txt, octobot_trading/__init__.py, octobot_trading/data_manager/candles_manager.py, requirements.txt, setup.py, tests/__init__.py, tests/exchanges/__init__.py, tests/exchanges/data/test_exchange_symbols_data.py, tests/exchanges/test_exchange_factory.py, tests/static/tentacles_config.json
Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/51
=> [CandleManager] Update shift usage

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/data/order.py, octobot_trading/exchanges/rest_exchange.py, octobot_trading/orders/order_adapter.py, octobot_trading/orders/order_util.py, octobot_trading/util/__init__.py, requirements.txt
Related to https://github.com/Drakkar-Software/OctoBot-Commons/pull/59
=> Remove dict_util get_or_default  

README.md
[![Coverage Status](https://coveralls.io/repos/github/Drakkar-Software/OctoBot-Trading/badge.svg?branch=master)](https://coveralls.io/github/Drakkar-Software/OctoBot-Trading?branch=master)
=> [Readme] Add coverage badge 

octobot_trading/api/modes.py, octobot_trading/exchanges/exchange_builder.pxd, octobot_trading/exchanges/exchange_builder.py, octobot_trading/modes/abstract_trading_mode.py
Required to connect to a service feed as a trading mode
=> add bot_id to trading modes

CHANGELOG.md, README.md, octobot_trading/__init__.py
- [OHLCVUpdater] Retry candle history loading
- [AbstractModeConsumer] Error handling
=> [Version] v1.6.2

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/producers/simulator/kline_updater_simulator.pxd, octobot_trading/producers/simulator/ohlcv_updater_simulator.pxd, octobot_trading/producers/simulator/order_book_updater_simulator.pxd, octobot_trading/producers/simulator/recent_trade_updater_simulator.pxd, octobot_trading/producers/simulator/ticker_updater_simulator.pxd, requirements.txt
- [Simulators] Time consumer cython declaration
=> [Version] v1.6.3

CHANGELOG.md, README.md, octobot_trading/__init__.py, requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/67
=> Bump requirements

octobot_trading/exchanges/exchange_manager.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/76
=> use common decrypt

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/exchange_simulator.pxd, octobot_trading/exchanges/exchange_simulator.py, octobot_trading/producers/simulator/ohlcv_updater_simulator.py
- [ExchangeSimulator] Time manager call
=> [Version] v1.6.12

octobot_trading/data_manager/orders_manager.pxd, octobot_trading/data_manager/orders_manager.py, octobot_trading/exchanges/data/exchange_personal_data.py, octobot_trading/exchanges/rest_exchange.py
can now create and handle filled real orders
=> Real trading fixes

CHANGELOG.md, Makefile, README.md, octobot_trading/__init__.py, requirements.txt, setup.py
=> [Version] v1.6.14

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/data/exchange_personal_data.py
- [ExchangePersonalData] Kwarg argument
=> [Version] v1.6.16

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/api/modes.py, octobot_trading/data/portfolio_profitability.py, octobot_trading/exchanges/websockets/websockets_util.py, octobot_trading/util/trading_config_util.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/88
=> Remove advanced manager

CHANGELOG.md, README.md, octobot_trading/__init__.py, requirements.txt, setup.py
=> [Version] v1.7.1

octobot_trading/exchanges/util/exchange_market_status_fixer.pxd, octobot_trading/exchanges/util/exchange_market_status_fixer.py, tests/exchanges/util/test_exchange_market_status_fixer.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/228 for CYTHON_IGNORE
=> update market status fixer

octobot_trading/data/portfolio.pxd, octobot_trading/data/portfolio.py, octobot_trading/data/sub_portfolio.py, octobot_trading/data_manager/portfolio_manager.pxd, octobot_trading/data_manager/portfolio_manager.py, octobot_trading/exchanges/data/exchange_personal_data.py
=> [Portfolio] Remove async methods

octobot_trading/data/portfolio_profitability.py, tests/data/test_portfolio_profitability.py, tests/util/random_numbers.py
=> [PortfolioProfitability] Add tests

octobot_trading/data_manager/portfolio_manager.pxd, octobot_trading/data_manager/portfolio_manager.py
None default value creates exceptions on real trading without being authenticated
=> fix portfolio default value

octobot_trading/data/order.py, octobot_trading/orders/types/limit/stop_loss_limit_order.py, octobot_trading/orders/types/limit/take_profit_limit_order.py, octobot_trading/orders/types/trailing/trailing_stop_limit_order.py, octobot_trading/traders/trader.py
Update portfolio from order before creating artificial order
=> [Order] Fix artificial order creation portfolio usage

octobot_trading/channels/orders.py, octobot_trading/data/order.py, octobot_trading/data_manager/orders_manager.pxd, octobot_trading/data_manager/orders_manager.py
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/249
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/248
=> [Order] Synchronize with exchange after creation

CHANGELOG.md, README.md, octobot_trading/__init__.py
- [Order] Synchronizing after creation on exchange
- [Order] Handling filled and cancelled events from exchange
- [OHLCVUpdater] Initialization exchange spam
=> [Version] v1.8.3

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/exchange_builder.py, octobot_trading/exchanges/exchange_manager.pxd, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/exchange_util.pxd, octobot_trading/exchanges/exchange_util.py, requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/46
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/91
=> handle exchange tentacles activation

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/channels/price.py, octobot_trading/data_manager/prices_manager.pxd, octobot_trading/data_manager/prices_manager.py, octobot_trading/enums.py, octobot_trading/exchanges/data/exchange_symbol_data.pxd, octobot_trading/exchanges/data/exchange_symbol_data.py, octobot_trading/producers/prices_updater.py, requirements.txt, setup.py, tests/data_manager/test_prices_manager.py, tests/orders/types/trailing/test_trailing_stop_order.py
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/274
=> [MarkPrice] Refactor mark price calculation

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/api/symbol_data.py
- [SymbolDataAPI] Fix missing mark price source argument in force_set_mark_price
=> [SymbolData] Fix missing mark price source arg in force set

octobot_trading/exchanges/rest_exchange.py, tests/exchanges/real_exchanges/__init__.py, tests/exchanges/real_exchanges/real_exchange_tester.py, tests/exchanges/real_exchanges/test_binance.py, tests/exchanges/real_exchanges/test_bitmax.py, tests/exchanges/real_exchanges/test_coinbasepro.py, tests/exchanges/real_exchanges/test_kucoin.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/290
=> Real exchange tests

octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/exchange_util.py, octobot_trading/exchanges/types/websocket_exchange.py, octobot_trading/exchanges/websockets/abstract_websocket.py, octobot_trading/exchanges/websockets/octobot_websocket.py, octobot_trading/exchanges/websockets/websockets_util.pxd, octobot_trading/exchanges/websockets/websockets_util.py, requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/52
=> add websocket activation checks

octobot_trading/api/modes.py, octobot_trading/consumers/octobot_channel_consumer.py, octobot_trading/errors/__init__.py, octobot_trading/exchanges/data/exchange_config_data.py, octobot_trading/exchanges/exchange_builder.py, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/exchanges.pxd, octobot_trading/exchanges/exchanges.py, octobot_trading/exchanges/rest_exchange.py
- fixes https://github.com/Drakkar-Software/OctoBot/issues/1290 "can't del exchange" and "no attribute 'split'" issues
- fixes "initialization impossible: GET https://api.crex24.com/v2/public/currencies" from 0.4 discord channel
=> handle trading mode incompatibility & sandbox issues

CHANGELOG.md, README.md, octobot_trading/__init__.py
- [OrderState] Tests async loop error
=> [Version] v1.9.1

octobot_trading/channels/orders.py
=> change missing order warning into debug message

octobot_trading/api/profitability.py, octobot_trading/channels/balance.py, octobot_trading/exchanges/data/exchange_personal_data.py, octobot_trading/portfolios/portfolio.pxd, octobot_trading/portfolios/portfolio.py, octobot_trading/portfolios/portfolio_manager.pxd, octobot_trading/portfolios/portfolio_manager.py, octobot_trading/portfolios/sub_portfolio.py, tests/portfolios/test_portfolio.py
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/330
Resolves #324
=> [Portfolio] Manage delta updates

CHANGELOG.md, README.md, octobot_trading/__init__.py
- [Portfolio] Balance delta update
- [PortfolioValueHolder] From PortfolioProfitability refactor
- [PortfolioProfitability] Refactor
=> [Version] v1.11.0

octobot_trading/channels/orders.py, octobot_trading/exchanges/exchange_channels.pxd, octobot_trading/exchanges/exchange_channels.py
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/344
=> [WebsocketExchange] Fix no order producer running when using WS

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/channels/orders.py, octobot_trading/exchanges/exchange_channels.pxd, octobot_trading/exchanges/exchange_channels.py
- ExchangeFactory from ExchangeManager refactor
- ExchangeChannels from ExchangeManager refactor
- ExchangeWebsocketFactory from ExchangeManager refactor
- [ExchangeManager] Refactor
- [Producers] Potential circular import
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/322
=> [Version] v1.11.1

octobot_trading/exchanges/types/future_exchange.pxd, octobot_trading/exchanges/types/future_exchange.py, tests/personal_data/portfolios/types/test_future_portfolio.py
=> [FutureExchange] Add future contract api

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/api/__init__.py, octobot_trading/api/profitability.py, octobot_trading/api/trader.py, octobot_trading/exchanges/exchange_builder.pxd, octobot_trading/exchanges/exchange_builder.py, octobot_trading/exchanges/exchange_manager.py, octobot_trading/modes/abstract_trading_mode.py, requirements.txt, tests/exchanges/__init__.py, tests/exchanges/test_exchange_factory.py, tests/static/config.json, tests/static/profile.json
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/145
=> enable profiles

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/connectors/ccxt_exchange.py, tests/exchanges/connectors/test_ccxt_exchange.py
- [CCXTExchange] NoneType when client.timeframes exists but is None
=> [Version] 1.11.23

CHANGELOG.md, README.md, octobot_trading/__init__.py, requirements.txt, setup.py
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/119
=> [Version] v1.11.28

CHANGELOG.md, README.md, octobot_trading/__init__.py, requirements.txt, setup.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/153
=> Bump numpy

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/personal_data/portfolios/portfolio.py, tests/personal_data/portfolios/test_portfolio.py
- Portfolio balance parsing None values
Should fix https://github.com/Drakkar-Software/OctoBot/issues/1548
=> [Version] v1.11.33

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/abstract_exchange.pxd, octobot_trading/exchanges/abstract_exchange.py, octobot_trading/personal_data/orders/order.py, octobot_trading/personal_data/orders/order_state.py, octobot_trading/personal_data/portfolios/portfolio.py, tests/personal_data/orders/states/test_order_state.py
Should resolves https://github.com/Drakkar-Software/OctoBot/issues/1559
=> [Orders] Fix attempt to refresh a self-managed order from exchange

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/constants.py, octobot_trading/enums.py, octobot_trading/personal_data/orders/states/cancel_order_state.pxd, octobot_trading/personal_data/orders/states/cancel_order_state.py, octobot_trading/personal_data/orders/states/fill_order_state.pxd, octobot_trading/personal_data/orders/states/fill_order_state.py, octobot_trading/personal_data/orders/states/order_state_factory.py, tests/personal_data/orders/states/test_cancel_order_state.py, tests/personal_data/orders/states/test_fill_order_state.py
Should resolve https://github.com/Drakkar-Software/OctoBot/issues/1552
=> [Order] Add support for expired, pending cancel and rejected status

CHANGELOG.md, README.md, octobot_trading/__init__.py, requirements.txt, setup.py
=> [Version] v1.11.36

octobot_trading/api/orders.py, octobot_trading/exchanges/traders/trader.py, octobot_trading/modes/channel/abstract_mode_producer.py, tests/exchanges/traders/test_trader.py
fixes https://github.com/Drakkar-Software/OctoBot-Trading/pull/471
=> [Trader] return cancel success on order cancel operation

octobot_trading/exchanges/exchange_config_data.py, requirements.txt, tests/exchanges/test_exchange_config_data.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/167
=> use CONFIG_SYMBOLS_WILDCARD for pairs configuration

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/enums.py, octobot_trading/exchanges/__init__.pxd, octobot_trading/exchanges/__init__.py, octobot_trading/exchanges/abstract_websocket_exchange.pxd, octobot_trading/exchanges/abstract_websocket_exchange.py, octobot_trading/exchanges/connectors/__init__.pxd, octobot_trading/exchanges/connectors/__init__.py, octobot_trading/exchanges/connectors/abstract_websocket_connector.pxd, octobot_trading/exchanges/connectors/abstract_websocket_connector.py, octobot_trading/exchanges/connectors/ccxt_websocket_connector.py, octobot_trading/exchanges/connectors/cryptofeed_websocket_connector.pxd, octobot_trading/exchanges/connectors/cryptofeed_websocket_connector.py, octobot_trading/exchanges/implementations/__init__.pxd, octobot_trading/exchanges/implementations/__init__.py, octobot_trading/exchanges/implementations/ccxt_websocket_exchange.py, octobot_trading/exchanges/implementations/cryptofeed_websocket_exchange.pxd, octobot_trading/exchanges/implementations/cryptofeed_websocket_exchange.py, octobot_trading/exchanges/types/websocket_exchange.pxd, octobot_trading/exchanges/types/websocket_exchange.py, requirements.txt, setup.py
Implemented : 
- Candle
- Kline
- OrderBook Ticker
- Recent trades
- L2 Book
Already tested : 
- Binance
- Bitmex
We'll be able to create easily WS tentacle to support unauthenticated feeds for : 
Bitcoin.com
Bitfinex
bitFlyer
BitMax
Bitstamp
Bittrex
Blockchain.com
Bybit
Binance
Binance Delivery
Binance Futures
Binance US
BitMEX
Coinbase
Deribit
EXX
FTX
FTX US
Gate.io
Gemini
HitBTC
Huobi
Huobi DM
Huobi Swap
Kraken
Kraken Futures
OKCoin
OKEx
Poloniex
ProBit
Upbit
It will also offer the possibility to create a whales alert tentacle.
=> Add cryptofeed websocket integration

requirements.txt, tests/exchanges/traders/test_trader.py, tests_additional/real_exchanges/real_exchange_tester.py, tests_additional/real_exchanges/test_ascendex.py, tests_additional/real_exchanges/test_binance.py, tests_additional/real_exchanges/test_bitfinex.py, tests_additional/real_exchanges/test_bithumb.py, tests_additional/real_exchanges/test_bitmax.py, tests_additional/real_exchanges/test_bitstamp.py, tests_additional/real_exchanges/test_bittrex.py, tests_additional/real_exchanges/test_coinbasepro.py, tests_additional/real_exchanges/test_crex24.py, tests_additional/real_exchanges/test_hitbtc.py, tests_additional/real_exchanges/test_huobi.py, tests_additional/real_exchanges/test_kraken.py, tests_additional/real_exchanges/test_kucoin.py, tests_additional/real_exchanges/test_okex.py, tests_additional/real_exchanges/test_upbit.py
requires https://github.com/ccxt/ccxt/pull/8804 and https://github.com/ccxt/ccxt/pull/8805 in a ccxt version
=> [exchange tests] add typing tests

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/personal_data/orders/order_adapter.py, tests/personal_data/orders/test_order_adapter.py
replaces https://github.com/Drakkar-Software/OctoBot-Trading/pull/501
=> Order adapter 2

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/modes/channel/abstract_mode_producer.pxd, octobot_trading/modes/channel/abstract_mode_producer.py
- AbstractModeProducer cryptocurrencies, symbols and timeframes wildcard subscription to MatrixChannel through boolean methods
=> [Version] v1.12.5

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/modes/abstract_trading_mode.py
Automate TradingMode producers and consumers creation
=> [Version] v1.12.6

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/util/__init__.pxd, octobot_trading/util/__init__.py, octobot_trading/util/config_util.pxd, octobot_trading/util/config_util.py, tests/util/test_config_util.py
- get_traded_pairs_by_currency to trading util (from flask_util)
Will be removed from flask_util when merged
=> [Version] v1.12.7

CHANGELOG.md, README.md, octobot_trading/__init__.py, requirements.txt, tests_additional/real_exchanges/test_bitfinex.py
fixes https://github.com/Drakkar-Software/OctoBot/issues/1666
=> [Requirements] update ccxt version

octobot_trading/exchanges/connectors/ccxt_exchange.py
first step to get more history ;)
=> Add since to get historical candle

octobot_trading/exchange_data/funding/channel/funding_updater.pxd, octobot_trading/exchange_data/funding/channel/funding_updater.py, octobot_trading/exchange_data/funding/channel/funding_updater_simulator.pxd, octobot_trading/exchange_data/funding/channel/funding_updater_simulator.py, octobot_trading/exchange_data/ohlcv/channel/ohlcv_updater_simulator.py, octobot_trading/exchange_data/ticker/channel/ticker_updater.py, octobot_trading/util/__init__.py, octobot_trading/util/simulator_updater_utils.py
Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/551
=> [FundingUpdater] Refactor

tests_additional/real_exchanges/test_poloniex.py
=> [ExchangesTests] Add poloniex

octobot_trading/exchanges/abstract_websocket_exchange.py, octobot_trading/exchanges/connectors/cryptofeed_websocket_connector.py, tests/exchanges/test_abstract_websocket_exchange.py
For example, when ticker is available in WS we don't need to subscribe to recent trade
Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/559
=> [AbstractWebsocketExchange] Add ignore feed when another is covering the same data

CHANGELOG.md, README.md, octobot_trading/__init__.py, requirements.txt
requires https://github.com/Drakkar-Software/trading-backend/pull/5
=> [Version] v1.13.2

octobot_trading/personal_data/portfolios/portfolio.py, requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/193
=> [Portfolio] use reentrant lock

octobot_trading/exchanges/connectors/ccxt_exchange.py
Fixes https://github.com/Drakkar-Software/OctoBot/issues/1785
=> [CCXTExchange] Fix unsupported fetchOrder 

octobot_trading/personal_data/orders/channel/orders_updater.py, octobot_trading/personal_data/orders/channel/orders_updater_simulator.py, octobot_trading/personal_data/orders/orders_manager.pxd, octobot_trading/personal_data/orders/orders_manager.py, octobot_trading/personal_data/orders/states/open_order_state.py
fixed negative portfolio error on initial order fetching
=> [OrderStates] skip portfolio available amount up on exchange orders init

octobot_trading/exchanges/exchange_manager.pxd, octobot_trading/exchanges/exchange_manager.py, requirements.txt
Requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/199
=> [ExchangeManager] Add exchange subaccount

.github/workflows/main.yml, CHANGELOG.md, README.md, octobot_trading/__init__.py, requirements.txt
Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/602
=> [Version] v1.13.13

octobot_trading/exchanges/types/websocket_exchange.py
=> [Websockets] do not start when nothing to watch

octobot_trading/enums.py, octobot_trading/exchanges/connectors/cryptofeed_websocket_connector.py, requirements.txt
Cryptofeed is preparing 2.0.0 update release
=> Update cryptofeed integration

octobot_trading/personal_data/positions/position.py
bybit raw position example: no quantity, we need to use size instead
=> [Positions] fix position parsing

octobot_trading/personal_data/orders/order.pxd, octobot_trading/personal_data/positions/position.pxd
fixes issues spotted here (PytestUnraisableExceptionWarning):
https://github.com/Drakkar-Software/OctoBot-Trading/runs/6536082756?check_suite_focus=true#step:6:406
=> [Cython] fix exception forwarding

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchange_data/ticker/channel/ticker_updater_simulator.pxd, octobot_trading/exchanges/config/__init__.pxd, octobot_trading/exchanges/config/exchange_config_data.pxd, octobot_trading/exchanges/exchange_manager.pxd, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/implementations/future_ccxt_exchange.pxd, octobot_trading/exchanges/implementations/spot_ccxt_exchange.pxd, octobot_trading/exchanges/traders/trader.pxd, octobot_trading/exchanges/traders/trader.py, octobot_trading/modes/channel/abstract_mode_producer.pxd, octobot_trading/personal_data/portfolios/portfolio_manager.pxd, octobot_trading/util/test_tools/spot_rest_exchange_test_tools.py, tests/exchanges/test_exchange_builder.py, tests/exchanges/test_exchanges.py
fixes https://github.com/Drakkar-Software/OctoBot-Tentacles/runs/6538580937?check_suite_focus=true#step:8:16
=> [Cython] fix header files

octobot_trading/modes/script_keywords/basic_keywords/run_persistence.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/252
=> [Scripting] add shared_elements api

octobot_trading/personal_data/orders/decimal_order_adapter.py
fixes https://github.com/Drakkar-Software/OctoBot/issues/1993
=> [Typing] fix typing issue

.github/workflows/cron.yml, octobot_trading/constants.py, octobot_trading/exchanges/connectors/ccxt_exchange.pxd, octobot_trading/exchanges/connectors/ccxt_exchange.py, octobot_trading/exchanges/implementations/future_ccxt_exchange.py, octobot_trading/exchanges/implementations/margin_ccxt_exchange.py, octobot_trading/exchanges/implementations/spot_ccxt_exchange.py, octobot_trading/personal_data/orders/order_util.pxd, octobot_trading/personal_data/orders/order_util.py, tests_additional/real_exchanges/test_bitget.py
Changes in exchanges are required to be able to define a custom ccxt connector (to get Bitget timeframes)
Used in https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/657
=> [Bitget] add Bitget compatibility

dev_requirements.txt, octobot_trading/modes/script_keywords/context_management.py, octobot_trading/modes/scripted_trading_mode/abstract_scripted_trading_mode.py, octobot_trading/util/__init__.pxd, octobot_trading/util/__init__.py, octobot_trading/util/config_util.pxd, octobot_trading/util/config_util.py, octobot_trading/util/databases_util.py
replaces https://github.com/Drakkar-Software/OctoBot-Trading/pull/713
contains only backtesting analysis settings and bot live id changes
=> add backtesting analysis settings

.github/workflows/cron.yml, octobot_trading/constants.py, tests_additional/real_exchanges/test_phemex.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/738
=> [Exchanges] add phemex

octobot_trading/modes/script_keywords/basic_keywords/user_inputs.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/282
=> [Scripted] add should_save_user_input param to user_inputs

octobot_trading/exchanges/traders/trader.py, octobot_trading/personal_data/orders/groups/balanced_take_profit_and_stop_order_group.py, octobot_trading/personal_data/orders/groups/one_cancels_the_other_order_group.py, octobot_trading/personal_data/orders/order_group.pxd, octobot_trading/personal_data/orders/order_group.py, octobot_trading/personal_data/orders/states/fill_order_state.py, octobot_trading/personal_data/state.py, tests/personal_data/orders/groups/test_one_cancels_the_other_order_group.py
Fixes https://github.com/Drakkar-Software/OctoBot-Trading/pull/765
=> State crash

octobot_trading/modes/script_keywords/basic_keywords/account_balance.py
TODO tag after this commit merge
=> [Keywords] fix typing issue

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/storage/abstract_storage.py, octobot_trading/storage/portfolio_storage.py, octobot_trading/storage/trades_storage.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/314
=> History push

octobot_trading/api/__init__.py, octobot_trading/api/portfolio.py
is required by PR in octobot commons
=> [Api] add get_global_portfolio_currencies_values

octobot_trading/exchanges/util/exchange_util.py
Should check for candle before operation
=> [DataCollector] fix get_historical_ohlcv

octobot_trading/personal_data/trades/trade.py
If the trade status is expired it now handle it properly
=> [Trade] properly handle status expired 

octobot_trading/modes/abstract_trading_mode.py, octobot_trading/modes/channel/abstract_mode_producer.py, octobot_trading/modes/script_keywords/context_management.py, octobot_trading/modes/scripted_trading_mode/abstract_scripted_trading_mode.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/322
=> [TradingModes] add trigger source

octobot_trading/api/storage.py, octobot_trading/personal_data/portfolios/history/historical_portfolio_value_manager.py, octobot_trading/personal_data/trades/trades_manager.py, octobot_trading/storage/abstract_storage.py, octobot_trading/storage/portfolio_storage.py, octobot_trading/storage/trades_storage.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/837
=> [Storages] only push new values

octobot_trading/constants.py, octobot_trading/enums.py, octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py, octobot_trading/exchanges/types/rest_exchange.py
This depends on [BinanceUsdM] PR in octobot-tentacles
=> [BinanceUsdM] add to default futures exchanges

octobot_trading/exchanges/abstract_exchange.py, octobot_trading/exchanges/traders/trader.py, octobot_trading/exchanges/types/rest_exchange.py
requires PR in tentacles -> [CreateOrder] add reduce only parameter
see binance usdm branch as an example
=> [CCXT] add reduce only to create order (future exchange tentacles must implement it)

CHANGELOG.md, README.md, octobot_trading/__init__.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/863
=> [Version] v2.3.26

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/abstract_exchange.pxd, octobot_trading/exchanges/abstract_exchange.py, octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py, octobot_trading/exchanges/connectors/simulator/exchange_simulator_connector.py, octobot_trading/exchanges/implementations/default_rest_exchange.py, octobot_trading/modes/abstract_trading_mode.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/347
=> generic tentacles user inputs config

octobot_trading/personal_data/orders/orders_manager.py, octobot_trading/signals/trading_signal_bundle_builder.py, tests/signals/test_trading_signal_bundle_builder.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/367
=> [Signals] properly handle chained and groupped orders signals

octobot_trading/exchange_data/ohlcv/channel/ohlcv_updater.py
(issue introduced in previous version)
=> [OHLCV] revert ohlcv updater symbols getter error

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/connectors/ccxt/ccxt_websocket_connector.py, octobot_trading/modes/mode_config.py, octobot_trading/modes/script_keywords/basic_keywords/account_balance.py, octobot_trading/modes/script_keywords/basic_keywords/amount.py, tests/modes/script_keywords/basic_keywords/test_amount.py, tests/personal_data/orders/test_order_util.py
allow to take leverage into account in any type of trading signal
=> [Orders] fix % amount type

octobot_trading/modes/channel/abstract_mode_consumer.py
will allow to track missing funds and such errors when creating orders
=> [TradingModes] store last order creation issue

octobot_trading/exchanges/exchange_channels.py
thanks to https://github.com/Drakkar-Software/OctoBot-Trading/commit/3f7e6c26a9f2a6d14b8c959d4c86687991832867#r123750016
=> [ExchangeChannels] fix typo

octobot_trading/exchanges/util/exchange_util.py, requirements.txt
requires https://github.com/Drakkar-Software/trading-backend/pull/39
=> Api permissions

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/config/exchange_config_data.py, octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py, octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py, octobot_trading/exchanges/connectors/simulator/ccxt_client_simulation.py, octobot_trading/exchanges/connectors/simulator/exchange_simulator_connector.py, octobot_trading/exchanges/exchange_builder.py, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/implementations/exchange_simulator.py, octobot_trading/exchanges/types/rest_exchange.py, octobot_trading/exchanges/util/exchange_util.py, octobot_trading/personal_data/portfolios/history/historical_portfolio_value_manager.py, octobot_trading/personal_data/portfolios/portfolio_manager.py, octobot_trading/util/test_tools/exchanges_test_tools.py, tests/personal_data/portfolios/history/test_historical_portfolio_value_manager.py
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/177
=> [Backtesting] enable RAM portfolio history

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/storage/abstract_storage.py, octobot_trading/storage/candles_storage.py, octobot_trading/storage/orders_storage.py, octobot_trading/storage/portfolio_storage.py, octobot_trading/storage/trades_storage.py, octobot_trading/storage/transactions_storage.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/388
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/954
=> Storage error

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/util/symbol_details.py, octobot_trading/util/test_tools/exchange_data.py, tests/exchanges/connectors/ccxt/mock_exchanges_data.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/390
=> Flex dataclass

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/exchanges/config/exchange_config_data.py
got broken here https://github.com/Drakkar-Software/OctoBot-Trading/commit/7147572449c01d09ee7b7db45d2151154bb403d8#diff-b00aa2e223c722c668dc9f4ae00acef0f08df92031b9bde68dad6bcc1d925924R273
=> [Exchanges] restore realtime timeframe on live exchanges

octobot_trading/api/portfolio.py, octobot_trading/personal_data/portfolios/value_converter.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/435
=> [ValueConverter] use commons is_usd_like_coin

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/modes/abstract_trading_mode.py, requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/449
=> handle historical config

octobot_trading/exchanges/types/rest_exchange.py, octobot_trading/exchanges/util/exchange_util.py
fixes OKX historical candles fetch on new markets
=> [Exchanges] handle MAX_FETCHED_OHLCV_COUNT

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/errors.py, octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py, octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/traders/trader.py, octobot_trading/exchanges/types/rest_exchange.py, tests_additional/real_exchanges/real_exchange_tester.py
replaces https://github.com/Drakkar-Software/OctoBot-Trading/pull/1164
=> Untradable error

octobot_trading/util/test_tools/exchanges_test_tools.py
asyncio.gather creates a managing task and adds extra complexity
=> [TestsTools] avoid creating extra tasks when possible

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/errors.py, octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py, octobot_trading/exchanges/exchange_builder.py, octobot_trading/exchanges/exchange_factory.py, octobot_trading/exchanges/exchange_manager.py, octobot_trading/exchanges/types/rest_exchange.py, octobot_trading/exchanges/util/exchange_util.py, requirements.txt
requires https://github.com/Drakkar-Software/trading-backend/pull/74
=>  add Key check

octobot_trading/personal_data/orders/order_util.py, tests/personal_data/orders/test_order_util.py
used in https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1483/commits/350580ec2afb92268417b707004f26517eefb572
=> [Orders] support custom volumes in split orders

octobot_trading/personal_data/portfolios/sub_portfolio_data.py, tests/personal_data/portfolios/test_sub_portfolio_data.py
error is now logged by the caller
=> [Portfolio] replace negatif pf error by warning

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/modes/abstract_trading_mode.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/464
=> Hist config

CHANGELOG.md, README.md, octobot_trading/__init__.py, octobot_trading/api/orders.py, octobot_trading/enums.py, octobot_trading/exchanges/traders/trader.py, octobot_trading/modes/abstract_trading_mode.py, octobot_trading/modes/channel/abstract_mode_consumer.py, octobot_trading/modes/channel/abstract_mode_producer.py, octobot_trading/modes/channel/mode.py, octobot_trading/modes/modes_util.py, octobot_trading/personal_data/orders/groups/balanced_take_profit_and_stop_order_group.py, octobot_trading/personal_data/orders/groups/one_cancels_the_other_order_group.py, octobot_trading/signals/__init__.py, octobot_trading/signals/signal_creation.py, octobot_trading/signals/trading_signal_bundle_builder.py, octobot_trading/signals/util.py, requirements.txt, tests/exchanges/traders/test_trader.py, tests/modes/test_abstract_mode_consumer.py, tests/modes/test_abstract_trading_mode.py, tests/modes/test_modes_util.py, tests/signals/test_util.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/468
=> Signals dependencies
